// `glassmkr-crucible init` subcommand: canonical first-run setup.
//
// Validates the API key, optionally probes the ingest endpoint to
// confirm it's accepted, writes or re-secures /etc/glassmkr/crucible.yaml
// as root-owned mode 0640, and writes a systemd unit at /etc/systemd/system/glassmkr-crucible
// (mode 0644) with ExecStart pointing at the dynamically-detected
// binary path (so Debian's /usr/local/bin/ vs Ubuntu's /usr/bin/
// divergence is handled), runs daemon-reload, and (unless --no-start)
// enables-and-starts the service.
//
// Legacy migration: if /etc/glassmkr/collector.yaml exists and the new
// path does not, init renames it via fs.renameSync() before any write.
// This is lossless and atomic on the same filesystem (/etc is always
// one mount). The systemd unit is regenerated to point at the new path
// and daemon-reload picks it up.
//
// Designed to run unprivileged for the validation/connectivity steps
// and require root for the filesystem and systemd writes (same as the
// agent itself). Errors are surfaced with non-zero exit codes.
//
// IO is injected via the InitDeps interface so unit tests can run
// without touching /etc, systemctl, or the network.

import * as fsDefault from "node:fs";
import { execFileSync as execFileSyncDefault } from "node:child_process";
import { randomUUID as randomUUIDDefault } from "node:crypto";
import * as osDefault from "node:os";
import * as pathDefault from "node:path";
import { buildSubprocessEnv } from "./lib/exec.js";
import {
  SERVICE_USER, WRAPPER_PATH, WRAPPER_SCRIPT, SUDOERS_PATH, SUDOERS_CONTENT,
} from "./lib/privileged.js";
import {
  assertEndpointResolution,
  createPinnedDispatcher,
  normalizeAllowedOrigins,
  undiciFetchImpl,
  validateEndpoint,
  type EndpointPolicy,
} from "./lib/endpoint-policy.js";

export const STATE_DIR = "/var/lib/glassmkr";
export const REBOOT_MARKER_DIR = "/var/lib/crucible";
export const ROOT_FALLBACK_ENV = "GLASSMKR_ALLOW_ROOT_FALLBACK";

class PrivilegeSetupFatalError extends Error {}

export interface InitOptions {
  apiKey?: string; // raw value, may be the literal "-" to mean "read from stdin"
  name?: string;
  ingestUrl?: string;
  configPath?: string;
  noStart?: boolean;
  force?: boolean;
  noVerify?: boolean; // skip the connectivity probe (default: probe)
  apiKeyFromArgv?: boolean;
  allowInsecureEndpoint?: boolean;
  allowedEndpointOrigins?: string[];
}

export interface InitDeps {
  fs: {
    existsSync: (p: string) => boolean;
    mkdirSync: (p: string, opts?: { recursive?: boolean; mode?: number }) => void;
    writeFileSync: (p: string, data: string, opts?: { mode?: number; flag?: string }) => void;
    chmodSync: (p: string, mode: number) => void;
    chownSync: (p: string, uid: number, gid: number) => void;
    lstatSync: (p: string) => {
      isSymbolicLink: boolean;
      isFile?: boolean;
      isDirectory?: boolean;
      uid: number;
      gid: number;
      mode: number;
    };
    realpathSync: (p: string) => string;
    writeSecureFileSync: (p: string, data: string, mode: number) => void;
    renameSync: (from: string, to: string) => void;
    unlinkSync: (p: string) => void;
  };
  exec: (cmd: string, args: string[]) => { stdout: string; status: number | null };
  hostname: () => string;
  log: (msg: string) => void;
  warn: (msg: string) => void;
  error: (msg: string) => void;
  fetch: typeof fetch;
  resolveEndpoint: typeof assertEndpointResolution;
  readStdin: () => Promise<string>;
  env: Readonly<Record<string, string | undefined>>;
}

export const DEFAULT_INGEST_URL = "https://app.glassmkr.com/api/v1/ingest";
// Single source of truth for these two paths is cli.ts; re-exported here so
// existing importers keep working (v1 freeze: they were defined twice).
export { DEFAULT_CONFIG_PATH, LEGACY_CONFIG_PATH } from "./cli.js";
import { DEFAULT_CONFIG_PATH, LEGACY_CONFIG_PATH } from "./cli.js";
export const SYSTEMD_UNIT_PATH = "/etc/systemd/system/glassmkr-crucible.service";

const KEY_RE_NEW = /^gmk_cru_live_[A-Za-z0-9]{20,}_[A-Za-z0-9]{4}$/;
const KEY_RE_LEGACY = /^col_[A-Fa-f0-9]{16,}$/;
const SYSTEMD_PATH_RE = /^\/[A-Za-z0-9_./:@+,-]+$/;
const SYSTEMD_USER_RE = /^[A-Za-z_][A-Za-z0-9_-]*$/;

export function isValidApiKey(key: string): boolean {
  if (!key || /\s/.test(key)) return false;
  return KEY_RE_NEW.test(key) || KEY_RE_LEGACY.test(key);
}

export function buildCollectorYaml(
  serverName: string,
  ingestUrl: string,
  apiKey: string,
  endpointPolicy: { allowInsecure?: boolean; allowedOrigins?: string[] } = {},
): string {
  // Hand-written so the format is human-readable, deterministic, and
  // doesn't pull in a YAML serializer at install time. Mirrors the
  // existing /etc/glassmkr/crucible.yaml shape (the file was renamed
  // from collector.yaml to crucible.yaml in v0.13.5; the on-disk
  // content layout did not change).
  return [
    `# Generated by 'glassmkr-crucible init'. Hand-edit if needed.`,
    `server_name: "${escapeDoubleQuoted(serverName)}"`,
    `collection:`,
    `  interval_seconds: 300`,
    `  ipmi: true`,
    `  smart: true`,
    `dashboard:`,
    `  enabled: true`,
    `  url: "${escapeDoubleQuoted(ingestUrl.replace(/\/api\/v1\/ingest$/, ""))}"`,
    `  api_key: "${apiKey}"`,
    `  allow_insecure_endpoint: ${endpointPolicy.allowInsecure ?? false}`,
    ...((endpointPolicy.allowedOrigins?.length ?? 0) > 0
      ? [`  allowed_origins:`, ...endpointPolicy.allowedOrigins!.map((origin) => `    - "${escapeDoubleQuoted(origin)}"`)]
      : [`  allowed_origins: []`]),
    ``,
  ].join("\n");
}

function escapeDoubleQuoted(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

export function buildSystemdUnit(binPath: string, configPath: string, user = SERVICE_USER): string {
  assertSafeSystemdPath(binPath, "binary path");
  assertSafeSystemdPath(configPath, "config path");
  if (!SYSTEMD_USER_RE.test(user)) throw new Error(`unsafe systemd user: ${user}`);
  return [
    `[Unit]`,
    `Description=Glassmkr Crucible - Bare Metal Monitoring`,
    `After=network.target`,
    ``,
    `[Service]`,
    `Type=simple`,
    // Run unprivileged by default. Root is emitted only after an operator
    // explicitly accepts the fallback through ROOT_FALLBACK_ENV.
    `User=${user}`,
    `ExecStart=${binPath} ${configPath}`,
    // LockPersonality, ProtectKernelTunables, and other directives that imply
    // NoNewPrivileges (see systemd.exec) are deliberately omitted. systemd forces
    // NoNewPrivileges=yes for them, and NoNewPrivileges=no cannot override
    // that implication. Classic sudo needs its setuid transition here.
    // read-only, NOT yes. `ProtectHome=yes` makes /home, /root and /run/user appear
    // EMPTY inside the service namespace, and GNU df omits filesystems it cannot
    // reach, so a real filesystem mounted anywhere under /home produced no DiskInfo
    // at all: no capacity alert, no inode alert, no read-only alert, silently. For a
    // disk-monitoring product that is a product failure, not a hardening win.
    // Adversarial review 2026-07-30, finding #5.
    //
    // `read-only` keeps the part that matters, the service still cannot WRITE there
    // (verified: `touch /home/<fs>/x` -> "Read-only file system"), while letting it
    // see that the filesystem exists and how full it is. Measured on a real host with
    // a loopback filesystem under /home: df inside the sandbox counted 0 of it under
    // `yes` and 1 under `read-only`.
    //
    // Exposure this adds, stated plainly: the service can now READ file contents under
    // /home and /root. No collector does: nothing in src/collect reads either path, so
    // this grants visibility we do not use, and it is the smallest change that stops
    // silently dropping a monitored filesystem. If that trade is ever unwanted, the
    // alternative is reporting such mounts as present-but-unmeasured, which needs an
    // agent-plus-dashboard contract change.
    `ProtectHome=read-only`,
    `PrivateTmp=yes`,
    `ProtectControlGroups=yes`,
    `ProtectSystem=strict`,
    // `-` prefix: tolerate a missing path so a fail-closed unprivileged unit whose
    // state dirs were not yet created never fails namespace setup (crash loop).
    `ReadWritePaths=-${STATE_DIR} -${REBOOT_MARKER_DIR}`,
    `Restart=always`,
    `RestartSec=10`,
    ``,
    `[Install]`,
    `WantedBy=multi-user.target`,
    ``,
  ].join("\n");
}

function assertSafeSystemdPath(value: string, label: string): void {
  if (!SYSTEMD_PATH_RE.test(value) || value.includes("//") || value.includes("/../") || value.endsWith("/..")) {
    throw new Error(`unsafe ${label}: ${JSON.stringify(value)}`);
  }
}

function ancestorDirectories(path: string): string[] {
  const out: string[] = [];
  let current = pathDefault.resolve(path);
  while (true) {
    out.push(current);
    if (current === pathDefault.parse(current).root) return out;
    current = pathDefault.dirname(current);
  }
}

function aclTrustFailure(deps: InitDeps, dir: string): string | null {
  const acl = deps.exec("getfacl", ["-cpn", dir]);
  if (acl.status === 0) {
    for (const raw of acl.stdout.split(/\r?\n/)) {
      const line = raw.replace(/\s*#.*$/, "").trim();
      if (/^(?:default:)?(?:user|group):[^:]+:[rwx-]*w[rwx-]*$/.test(line)) {
        return `${dir} has a named ACL entry granting write: ${line}`;
      }
    }
    return null;
  }

  const ls = deps.exec("ls", ["-ldn", dir]);
  if (ls.status !== 0) return `cannot inspect ACLs on ${dir}`;
  const mode = ls.stdout.trim().split(/\s+/, 1)[0] ?? "";
  if (mode.endsWith("+")) return `${dir} has ACLs but getfacl is unavailable`;
  return null;
}

/**
 * A wrapper directory is trustworthy iff it is root-owned and NOT writable by
 * the service user: not world-writable, and not group-writable by any group the
 * service user belongs to. Returns a human-readable failure reason, or null when
 * safe. `serviceGids` must be the service user's FINAL group set.
 */
function dirTrustFailure(deps: InitDeps, dir: string, serviceGids: number[]): string | null {
  let st: ReturnType<InitDeps["fs"]["lstatSync"]>;
  try {
    st = deps.fs.lstatSync(dir);
  } catch (err: any) {
    return `cannot stat ${dir}: ${err?.message ?? err}`;
  }
  if (st.isSymbolicLink) return `${dir} is a symbolic link`;
  if (st.isDirectory === false) return `${dir} is not a directory`;
  if (st.uid !== 0) return `${dir} is not root-owned (uid=${st.uid})`;
  if ((st.mode & 0o002) !== 0) return `${dir} is world-writable (mode=${(st.mode & 0o777).toString(8)})`;
  if ((st.mode & 0o020) !== 0 && serviceGids.includes(st.gid)) {
    return `${dir} is group-writable by a group '${SERVICE_USER}' belongs to (gid=${st.gid})`;
  }
  return aclTrustFailure(deps, dir);
}

function strictRootDirectoryFailure(deps: InitDeps, dir: string): string | null {
  const problem = dirTrustFailure(deps, dir, []);
  if (problem) return problem;
  const st = deps.fs.lstatSync(dir);
  if ((st.mode & 0o020) !== 0) return `${dir} is group-writable`;
  return null;
}

/**
 * Remove the sudo grant and the wrapper. Called on every fail-safe path so a box
 * that cannot be made safe (or an upgrade that detects an unsafe directory) never
 * leaves a NOPASSWD grant pointing at a service-user-tamperable wrapper.
 *
 * Returns true iff the escalation grant is provably gone. The sudoers drop-in is
 * removed FIRST (it is the thing that enables escalation); if it cannot be
 * unlinked (an immutable file, an I/O or permission error) we fall back to
 * overwriting it with an inert comment so no NOPASSWD line survives. Only when
 * BOTH the unlink AND the neutralizing overwrite fail do we return false, so the
 * caller can surface a loud warning instead of assuming the path was closed.
 * (Codex 2026-07-18 #1: a swallowed unlinkSync error previously left a live grant
 * while the wrapper directory was still service-user-writable, so glassmkr could
 * recreate the wrapper and escalate through the surviving rule.)
 */
function revokePrivilegeSeparation(deps: InitDeps): boolean {
  for (const tmp of [`${SUDOERS_PATH}.tmp`, `${WRAPPER_PATH}.tmp`]) {
    try {
      if (deps.fs.existsSync(tmp)) deps.fs.unlinkSync(tmp);
    } catch {
      deps.warn(`[init] could not remove stale privilege setup file ${tmp}; remove it before retrying.`);
    }
  }
  let grantGone = false;
  try {
    if (deps.fs.existsSync(SUDOERS_PATH)) deps.fs.unlinkSync(SUDOERS_PATH);
    grantGone = true;
  } catch {
    try {
      deps.fs.writeFileSync(SUDOERS_PATH, "# glassmkr privilege separation revoked\n", { mode: 0o440 });
      grantGone = true; // the NOPASSWD line is gone even though the inode remains
    } catch { grantGone = false; }
  }
  // The wrapper is inert once the grant is gone, but remove it for hygiene.
  try {
    if (deps.fs.existsSync(WRAPPER_PATH)) deps.fs.unlinkSync(WRAPPER_PATH);
  } catch { /* best effort: harmless without the grant, which is handled above */ }
  return grantGone;
}

/**
 * Establish the §2.1 privilege boundary: an unprivileged `glassmkr` system user
 * that escalates only through the root-owned sudo wrapper. Idempotent; safe to
 * run on every install/upgrade. Returns true iff the box is fully ready to run
 * the service as `glassmkr`. On ANY hard failure it returns false, REVOKES any
 * partial/prior grant. The service remains unprivileged on ordinary wrapper
 * failures. A failure that prevents the service user from running safely, or that
 * leaves an escalation grant live, throws so init cannot install or start a unit.
 *
 * Order matters (Codex re-review 2026-07-18): group memberships are applied
 * FIRST, then the wrapper directory chain is trust-checked against the service
 * user's FINAL groups, and only THEN is the wrapper written (into a
 * known-untamperable dir) and the sudoers grant installed. Checking the dir
 * before writing the temp file also closes a symlink-preplant hole.
 */
export function setupPrivilegeSeparation(deps: InitDeps, configPath: string): boolean {
  const fail = (msg: string, fatal = false): false => {
    const revoked = revokePrivilegeSeparation(deps);
    if (!revoked) {
      throw new PrivilegeSetupFatalError(`${msg}; could not remove the sudo grant at ${SUDOERS_PATH}. An escalation path may remain; remove it by hand before retrying.`);
    }
    if (fatal) throw new PrivilegeSetupFatalError(msg);
    deps.warn(`[init] ${msg}; privileged wrapper disabled and service remains User=${SERVICE_USER}.`);
    return false;
  };

  // 1. Service user (system, no login, no home).
  const idr = deps.exec("id", ["-u", SERVICE_USER]);
  if (idr.status !== 0) {
    const ur = deps.exec("useradd", [
      "--system", "--no-create-home", "--shell", "/usr/sbin/nologin", SERVICE_USER,
    ]);
    if (ur.status !== 0) return fail(`could not create '${SERVICE_USER}' user (status=${ur.status})`, true);
    deps.log(`[init] created system user '${SERVICE_USER}'.`);
  }

  // 2. Grant only journal access. Remove a legacy adm membership installed by
  //    older Crucible releases without touching operator-managed groups.
  const journalGroup = deps.exec("getent", ["group", "systemd-journal"]);
  if (journalGroup.status === 0) {
    const addJournal = deps.exec("usermod", ["-aG", "systemd-journal", SERVICE_USER]);
    if (addJournal.status !== 0) deps.warn(`[init] could not add '${SERVICE_USER}' to systemd-journal; failed-unit excerpts may be unavailable.`);
  } else {
    deps.warn(`[init] systemd-journal group is absent; failed-unit excerpts may be unavailable.`);
  }
  const admGroup = deps.exec("getent", ["group", "adm"]);
  const admMembers = admGroup.status === 0 ? (admGroup.stdout.split(":")[3] ?? "").trim().split(",") : [];
  if (admMembers.includes(SERVICE_USER)) {
    const removeAdm = deps.exec("gpasswd", ["-d", SERVICE_USER, "adm"]);
    if (removeAdm.status !== 0) return fail(`could not remove broad adm membership from '${SERVICE_USER}'`);
  }

  // 3. Trust every wrapper ancestor against the FINAL groups. A
  //    tamperable ancestor can replace the directory below it
  //    means the root-owned wrapper could be swapped and run as root through the
  //    NOPASSWD grant. Refuse (and revoke any prior grant) rather than assume.
  const gout = deps.exec("id", ["-G", SERVICE_USER]);
  if (gout.status !== 0) return fail(`could not read '${SERVICE_USER}' groups (id -G status=${gout.status})`);
  const serviceGids = gout.stdout.trim().split(/\s+/).filter(Boolean).map((n) => Number(n));
  if (serviceGids.length === 0 || serviceGids.some((n) => !Number.isFinite(n))) return fail(`could not parse '${SERVICE_USER}' group ids from: ${gout.stdout.trim()}`);

  try {
    deps.fs.chownSync(configPath, 0, serviceGids[0]);
    deps.fs.chmodSync(configPath, 0o640);
    const configStat = deps.fs.lstatSync(configPath);
    if (configStat.isSymbolicLink || configStat.isFile === false || configStat.uid !== 0 || configStat.gid !== serviceGids[0] || (configStat.mode & 0o777) !== 0o640) {
      return fail(`config ${configPath} failed its post-install safety check`);
    }
    // A POSIX ACL survives chmod (chmod only adjusts the ACL mask), so a named-user
    // read ACL on the key-bearing config would still leak it despite mode 0640.
    // Strip all extended ACLs, then refuse if any remains or cannot be inspected.
    deps.exec("setfacl", ["-b", configPath]);
    const aclLs = deps.exec("ls", ["-ldn", configPath]);
    if (aclLs.status !== 0) return fail(`could not inspect ACLs on ${configPath}`);
    if ((aclLs.stdout.trim().split(/\s+/, 1)[0] ?? "").endsWith("+")) {
      return fail(`${configPath} still carries an extended ACL after setfacl -b`);
    }
  } catch (err: any) {
    return fail(`could not secure ${configPath}: ${err?.message ?? err}`);
  }

  // 3b. Create the writable state dirs BEFORE the wrapper/sudoers steps so the
  //     fail-closed unprivileged path always has them: the hardened unit's
  //     ReadWritePaths references these, and an ordinary wrapper/sudoers failure
  //     returns before any later step. Marker dir stays root-owned; state dir is
  //     service-owned.
  try { deps.fs.mkdirSync(STATE_DIR, { recursive: true, mode: 0o750 }); } catch { /* exists */ }
  const stateChown = deps.exec("chown", ["-R", `${SERVICE_USER}:${SERVICE_USER}`, STATE_DIR]);
  if (stateChown.status !== 0) return fail(`could not chown ${STATE_DIR} to ${SERVICE_USER} (status=${stateChown.status})`);
  try { deps.fs.mkdirSync(REBOOT_MARKER_DIR, { recursive: true, mode: 0o2770 }); } catch { /* exists */ }
  const markerChown = deps.exec("chown", [`root:${SERVICE_USER}`, REBOOT_MARKER_DIR]);
  if (markerChown.status !== 0) return fail(`could not set ${REBOOT_MARKER_DIR} ownership (status=${markerChown.status})`);
  try { deps.fs.chmodSync(REBOOT_MARKER_DIR, 0o2770); } catch (err: any) {
    return fail(`could not set ${REBOOT_MARKER_DIR} mode: ${err?.message ?? err}`);
  }

  const wrapperDir = pathDefault.dirname(WRAPPER_PATH);
  for (const dir of ancestorDirectories(wrapperDir)) {
    const problem = dirTrustFailure(deps, dir, serviceGids);
    if (problem) return fail(`wrapper directory chain is not trustworthy: ${problem}`);
  }

  // 5. The collection wrapper. The dir is now known un-writable by the service
  //    user, so build a FRESH root-owned temp file (O_EXCL via flag "wx", so a
  //    pre-planted symlink is never followed), chown root, atomically rename into
  //    place (replacing any pre-existing file/symlink), then lstat-verify.
  const wrapperTmp = `${WRAPPER_PATH}.tmp`;
  try {
    try { if (deps.fs.existsSync(wrapperTmp)) deps.fs.unlinkSync(wrapperTmp); } catch { /* re-created below */ }
    deps.fs.writeFileSync(wrapperTmp, WRAPPER_SCRIPT, { mode: 0o755, flag: "wx" });
    deps.fs.chmodSync(wrapperTmp, 0o755);
    deps.fs.chownSync(wrapperTmp, 0, 0);
    deps.fs.renameSync(wrapperTmp, WRAPPER_PATH);
    const st = deps.fs.lstatSync(WRAPPER_PATH);
    if (st.isSymbolicLink || st.uid !== 0 || st.gid !== 0 || (st.mode & 0o022) !== 0) {
      return fail(`wrapper ${WRAPPER_PATH} failed its post-install safety check (symlink=${st.isSymbolicLink}, uid=${st.uid}, gid=${st.gid}, mode=${(st.mode & 0o777).toString(8)})`);
    }
  } catch (err: any) {
    return fail(`could not install wrapper ${WRAPPER_PATH}: ${err?.message ?? err}`);
  }

  // 6. Sudoers drop-in, validated with `visudo -cf` on a temp file BEFORE it goes
  //    live (a malformed sudoers file breaks sudo host-wide).
  const sudoersTmp = `${SUDOERS_PATH}.tmp`;
  try {
    deps.fs.writeFileSync(sudoersTmp, SUDOERS_CONTENT, { mode: 0o440 });
    const chk = deps.exec("visudo", ["-cf", sudoersTmp]);
    if (chk.status !== 0) return fail(`visudo rejected the sudoers drop-in (status=${chk.status})`);
    deps.fs.renameSync(sudoersTmp, SUDOERS_PATH);
    deps.fs.chmodSync(SUDOERS_PATH, 0o440);
  } catch (err: any) {
    return fail(`could not install sudoers ${SUDOERS_PATH}: ${err?.message ?? err}`);
  }

  deps.log(`[init] privilege separation ready: service will run as '${SERVICE_USER}' via ${WRAPPER_PATH}.`);
  return true;
}

function stopLegacyRootUnitAfterFatalSetup(deps: InitDeps): void {
  let existingUnit: { stdout: string; status: number | null };
  try {
    existingUnit = deps.exec("systemctl", ["cat", "glassmkr-crucible.service", "--no-pager"]);
  } catch (err: any) {
    deps.error(`[init] WARNING: could not inspect the existing service after a fatal privilege setup error: ${err?.message ?? err}. If it runs as root, stop it now with 'sudo systemctl stop glassmkr-crucible'.`);
    return;
  }
  const configuredUsers = [...existingUnit.stdout.matchAll(/^\s*User\s*=\s*(\S+)\s*$/gmi)];
  if (existingUnit.status !== 0 || configuredUsers.at(-1)?.[1].toLowerCase() !== "root") return;

  let stopped = false;
  try {
    stopped = deps.exec("systemctl", ["stop", "glassmkr-crucible"]).status === 0;
  } catch {
    stopped = false;
  }
  if (stopped) {
    deps.warn("[init] SECURITY: stopped the existing User=root service after fatal privilege setup failure.");
  } else {
    deps.error("[init] SECURITY WARNING: the existing service uses User=root and could not be stopped. Run 'sudo systemctl stop glassmkr-crucible' immediately.");
  }
}

/**
 * Run the init flow with caller-provided IO. Returns the exit code
 * (0 = success). Pure orchestration; no side effects on `process`.
 */
export async function runInit(opts: InitOptions, deps: InitDeps): Promise<number> {
  let rawIngestUrl = opts.ingestUrl ?? DEFAULT_INGEST_URL;
  // Convenience for self-hosted dashboards (v1 freeze): a bare base URL
  // ("http://host:3000") gets the canonical ingest path appended, because a
  // pathless URL would otherwise POST to "/" and fail only at push time,
  // after init reported success. An explicit non-root path is respected
  // as-is; an unparseable URL falls through to validateEndpoint's error.
  if (opts.ingestUrl) {
    try {
      const u = new URL(rawIngestUrl);
      if (u.pathname === "/" && !u.search && !u.hash) {
        u.pathname = "/api/v1/ingest";
        rawIngestUrl = u.toString();
        deps.log(`[init] --ingest-url has no path; using ${rawIngestUrl}`);
      }
    } catch { /* validateEndpoint below reports the real error */ }
  }
  const configPath = opts.configPath ?? DEFAULT_CONFIG_PATH;
  const isCanonicalPath = configPath === DEFAULT_CONFIG_PATH;
  const repairMode = !opts.force && (
    deps.fs.existsSync(configPath)
    || (isCanonicalPath && deps.fs.existsSync(LEGACY_CONFIG_PATH))
  );

  // Resolve API key (stdin form supports `--api-key -`).
  let apiKey = opts.apiKey ?? "";
  if (apiKey && apiKey !== "-" && (opts.apiKeyFromArgv ?? true)) {
    deps.warn("[init] WARNING: literal --api-key values are visible in process listings and shell history. Prefer --api-key - and provide the key on stdin.");
  }
  if (apiKey === "-") {
    try {
      apiKey = (await deps.readStdin()).replace(/\r?\n$/, "").trim();
    } catch (err: any) {
      deps.error(`[init] failed to read api key from stdin: ${err?.message ?? err}`);
      return 1;
    }
  }
  if (!repairMode && !isValidApiKey(apiKey)) {
    deps.error(`[init] invalid --api-key: must look like "gmk_cru_live_<...>_<4>" or "col_<hex>". Got ${apiKey.length} char(s).`);
    return 2;
  }

  const serverName = opts.name && opts.name.trim() ? opts.name.trim() : deps.hostname();
  let endpointPolicy: EndpointPolicy;
  let ingestEndpoint: URL | undefined;
  let ingestUrl = rawIngestUrl;
  try {
    endpointPolicy = {
      allowInsecure: opts.allowInsecureEndpoint ?? false,
      allowedOrigins: normalizeAllowedOrigins(opts.allowedEndpointOrigins),
    };
    if (!repairMode) {
      ingestEndpoint = validateEndpoint(rawIngestUrl, endpointPolicy);
      await deps.resolveEndpoint(ingestEndpoint, endpointPolicy);
      ingestUrl = ingestEndpoint.toString();
    }
  } catch (err: any) {
    deps.error(`[init] refusing ingest endpoint: ${err?.message ?? err}. For a trusted self-hosted endpoint, pass --allow-insecure-endpoint or --allow-endpoint-origin.`);
    return 14;
  }

  try {
    assertSafeSystemdPath(configPath, "config path");
  } catch (err: any) {
    deps.error(`[init] ${err?.message ?? err}`);
    return 5;
  }

  const parent = pathDefault.dirname(configPath);
  try {
    deps.fs.mkdirSync(parent, { recursive: true, mode: 0o755 });
    for (const dir of ancestorDirectories(parent)) {
      const problem = strictRootDirectoryFailure(deps, dir);
      if (problem) throw new Error(problem);
    }
  } catch (err: any) {
    deps.error(`[init] config directory chain is not trustworthy: ${err?.message ?? err}`);
    return 5;
  }

  // Connectivity probe (optional). 401 means key is wrong → hard fail.
  // 5xx / network errors → warn but continue (the host's network may
  // still be coming up during a fresh install).
  if (!repairMode && !opts.noVerify) {
    const initialOrigin = ingestEndpoint!.origin;
    let current = ingestEndpoint!;
    let probeComplete = false;
    deps.log(`[init] probing ${current} ...`);
    for (let redirectCount = 0; redirectCount <= 3; redirectCount++) {
      let addresses;
      try {
        addresses = await deps.resolveEndpoint(current, endpointPolicy);
      } catch (err: any) {
        deps.error(`[init] refusing ingest endpoint resolution: ${err?.message ?? err}`);
        return 14;
      }
      const dispatcher = createPinnedDispatcher(current, addresses, endpointPolicy);
      let resp: Response;
      try {
        resp = await deps.fetch(current, {
          method: "GET",
          headers: { Authorization: `Bearer ${apiKey}` },
          redirect: "manual",
          dispatcher,
          signal: AbortSignal.timeout(8000),
        } as RequestInit);
      } catch (err: any) {
        await dispatcher.close();
        deps.warn(`[init] connectivity probe failed: ${err?.message ?? err}. Continuing; verify after install with 'journalctl -u glassmkr-crucible'.`);
        probeComplete = true;
        break;
      }
      if ([301, 302, 303, 307, 308].includes(resp.status)) {
        const location = resp.headers.get("location");
        await resp.body?.cancel();
        await dispatcher.close();
        if (!location) {
          deps.error("[init] refusing ingest redirect without a location");
          return 14;
        }
        try {
          current = validateEndpoint(new URL(location, current).toString(), endpointPolicy, initialOrigin);
        } catch (err: any) {
          deps.error(`[init] refusing ingest redirect: ${err?.message ?? err}`);
          return 14;
        }
        continue;
      }
      await resp.body?.cancel();
      await dispatcher.close();
      if (resp.status === 401 || resp.status === 403) {
        deps.error(`[init] api key rejected by ${current} (HTTP ${resp.status}). Double-check the key in your Glassmkr dashboard.`);
        return 3;
      }
      if (resp.status >= 500) {
        deps.warn(`[init] ingest endpoint returned ${resp.status}; continuing anyway. Check connectivity post-install.`);
      } else {
        deps.log(`[init] api key validated (HTTP ${resp.status}).`);
      }
      probeComplete = true;
      break;
    }
    if (!probeComplete) {
      deps.error("[init] refusing ingest endpoint after too many redirects");
      return 14;
    }
  }

  // Legacy migration: if the operator is initing into the canonical
  // /etc/glassmkr/crucible.yaml path AND a legacy /etc/glassmkr/collector.yaml
  // file is present AND the new file is not, rename it lossless into
  // place. This preserves any hand-edits (telegram tokens, custom
  // thresholds, tls_pin) the operator added since the original install.
  // If both files exist we leave the legacy file alone and warn the
  // operator so they can resolve the divergence; --force on top of a
  // populated new path is the normal overwrite path and the legacy
  // file becomes irrelevant.
  const legacyPresent = isCanonicalPath && deps.fs.existsSync(LEGACY_CONFIG_PATH);
  const newPresent = deps.fs.existsSync(configPath);
  if (newPresent) {
    try {
      const target = deps.fs.lstatSync(configPath);
      const serviceUidResult = deps.exec("id", ["-u", SERVICE_USER]);
      const serviceUid = Number(serviceUidResult.stdout.trim());
      const allowedOwner = target.uid === 0 || (serviceUidResult.status === 0 && Number.isFinite(serviceUid) && target.uid === serviceUid);
      if (target.isSymbolicLink || target.isFile === false || !allowedOwner || (target.mode & 0o022) !== 0) {
        deps.error(`[init] refusing unsafe config target at ${configPath}`);
        return 4;
      }
    } catch (err: any) {
      deps.error(`[init] could not inspect existing config ${configPath}: ${err?.message ?? err}`);
      return 4;
    }
  }
  let justMigrated = false;
  if (legacyPresent && !newPresent) {
    try {
      const legacy = deps.fs.lstatSync(LEGACY_CONFIG_PATH);
      const serviceUidResult = deps.exec("id", ["-u", SERVICE_USER]);
      const serviceUid = Number(serviceUidResult.stdout.trim());
      const allowedOwner = legacy.uid === 0 || (serviceUidResult.status === 0 && Number.isFinite(serviceUid) && legacy.uid === serviceUid);
      if (legacy.isSymbolicLink || legacy.isFile === false || !allowedOwner || (legacy.mode & 0o022) !== 0) {
        throw new Error("legacy config is not a safe regular file owned by root or the service user");
      }
      deps.fs.renameSync(LEGACY_CONFIG_PATH, configPath);
      justMigrated = true;
      deps.log(`[init] migrated legacy config: ${LEGACY_CONFIG_PATH} -> ${configPath}`);
    } catch (err: any) {
      deps.error(`[init] failed to migrate legacy config ${LEGACY_CONFIG_PATH} -> ${configPath}: ${err?.message ?? err}`);
      return 6;
    }
  } else if (legacyPresent && newPresent) {
    deps.warn(`[init] both ${LEGACY_CONFIG_PATH} and ${configPath} exist; leaving the legacy file in place. After init, remove the legacy file with: sudo rm ${LEGACY_CONFIG_PATH}`);
  }

  // Write config (0600) unless repair mode preserves the existing bytes. A file
  // that arrived via the legacy migration just above counts as "the
  // operator's existing config" and is preserved without rewrite (the
  // explicit migration log line above tells them what happened).
  if (justMigrated) {
    deps.log(`[init] preserved migrated config at ${configPath} (no rewrite). To regenerate from scratch, re-run with --force.`);
  } else if (deps.fs.existsSync(configPath) && !opts.force) {
    deps.log(`[init] preserving existing config at ${configPath}; ownership and mode will be re-secured.`);
  }

  // Skip rewrite when we just migrated the legacy file into place;
  // operator-edited content (telegram tokens, custom thresholds, tls_pin)
  // is preserved verbatim. --force still re-generates from scratch by
  // overwriting unconditionally.
  if ((!justMigrated && !repairMode) || opts.force) {
    const yaml = buildCollectorYaml(serverName, ingestUrl, apiKey, {
      allowInsecure: opts.allowInsecureEndpoint,
      allowedOrigins: opts.allowedEndpointOrigins,
    });
    const configTmp = `${configPath}.tmp-${randomUUIDDefault()}`;
    try {
      deps.fs.writeSecureFileSync(configTmp, yaml, 0o600);
      deps.fs.renameSync(configTmp, configPath);
      deps.log(`[init] wrote config: ${configPath} (mode 0600, server_name=${serverName})`);
    } catch (err: any) {
      try { if (deps.fs.existsSync(configTmp)) deps.fs.unlinkSync(configTmp); } catch { /* best effort */ }
      deps.error(`[init] failed to write ${configPath}: ${err?.message ?? err}`);
      return 6;
    }
  }

  // Resolve binary path via `command -v`. Mirrors the F5 install fix.
  let binPath: string | null = null;
  try {
    const r = deps.exec("command", ["-v", "glassmkr-crucible"]);
    const candidate = r.stdout.trim();
    if (candidate) binPath = candidate;
  } catch {
    // fall through; we'll try `which` next
  }
  if (!binPath) {
    try {
      const r = deps.exec("which", ["glassmkr-crucible"]);
      const candidate = r.stdout.trim();
      if (candidate) binPath = candidate;
    } catch {
      // ignored
    }
  }
  if (!binPath) {
    deps.error(`[init] could not locate the glassmkr-crucible binary on PATH. Make sure 'npm install -g @glassmkr/crucible' completed before running init.`);
    return 7;
  }

  try {
    assertSafeSystemdPath(binPath, "binary path");
    const resolvedBin = deps.fs.realpathSync(binPath);
    assertSafeSystemdPath(resolvedBin, "resolved binary path");
    const binStat = deps.fs.lstatSync(resolvedBin);
    if (binStat.isSymbolicLink || binStat.isFile === false || binStat.uid !== 0 || (binStat.mode & 0o022) !== 0) {
      throw new Error(`binary must be a root-owned regular file and not group/world-writable: ${resolvedBin}`);
    }
  } catch (err: any) {
    deps.error(`[init] refusing unsafe glassmkr-crucible binary: ${err?.message ?? err}`);
    return 7;
  }

  // §2.1: establish the unprivileged-user + sudo-wrapper boundary. Runs
  // AFTER the config is written (so it can hand ownership to the service
  // user) and BEFORE the unit is written (so the escalation path exists
  // before the unit runs as User=glassmkr). Ordinary wrapper failures remain
  // unprivileged. Root requires an exact, explicit operator opt-out.
  let privilegeReady: boolean;
  try {
    privilegeReady = setupPrivilegeSeparation(deps, configPath);
  } catch (err) {
    deps.error(`[init] privilege setup failed closed: ${err instanceof Error ? err.message : String(err)}`);
    stopLegacyRootUnitAfterFatalSetup(deps);
    return 10;
  }
  let serviceUser = SERVICE_USER;
  if (!privilegeReady) {
    if (deps.env[ROOT_FALLBACK_ENV] === "1") {
      serviceUser = "root";
      deps.warn(`[init] SECURITY OVERRIDE: ${ROOT_FALLBACK_ENV}=1 accepted; running the full collector as root because wrapper setup failed.`);
    } else {
      deps.error(`[init] privileged collectors are unavailable until wrapper setup is repaired. The core service will run as '${SERVICE_USER}'. Set ${ROOT_FALLBACK_ENV}=1 only to explicitly accept full root execution.`);
    }
  }

  // Write systemd unit (0644).
  try {
    const unit = buildSystemdUnit(binPath, configPath, serviceUser);
    deps.fs.writeFileSync(SYSTEMD_UNIT_PATH, unit, { mode: 0o644 });
    deps.fs.chmodSync(SYSTEMD_UNIT_PATH, 0o644);
    deps.log(`[init] wrote systemd unit: ${SYSTEMD_UNIT_PATH} (ExecStart=${binPath})`);
  } catch (err: any) {
    deps.error(`[init] failed to write systemd unit: ${err?.message ?? err}`);
    return 8;
  }

  // daemon-reload to pick up the new unit.
  try {
    const r = deps.exec("systemctl", ["daemon-reload"]);
    if (r.status !== 0) {
      deps.warn(`[init] systemctl daemon-reload returned ${r.status}; continuing.`);
    }
  } catch (err: any) {
    deps.warn(`[init] systemctl daemon-reload failed: ${err?.message ?? err}; continuing.`);
  }

  if (opts.noStart) {
    deps.log(`[init] --no-start set; not enabling/starting glassmkr-crucible.`);
    deps.log(`[init] when ready: 'sudo systemctl enable --now glassmkr-crucible'`);
    return 0;
  }

  // enable (persist across boot) THEN restart. `enable --now` only STARTS the
  // unit, which is a no-op when the service is already running: on an upgrade
  // that just rewrote User= or applied new supplementary groups, the
  // already-running process would keep
  // its old credentials, so privileged collectors return null until a manual
  // restart. restart applies the new unit unconditionally, and starts the unit
  // when it is stopped (fresh install), so it is correct in both cases.
  // (Codex 2026-07-18 #2.)
  try {
    const en = deps.exec("systemctl", ["enable", "glassmkr-crucible"]);
    if (en.status !== 0) {
      deps.warn(`[init] systemctl enable returned ${en.status}; continuing to (re)start.`);
    }
    const r = deps.exec("systemctl", ["restart", "glassmkr-crucible"]);
    if (r.status !== 0) {
      deps.error(`[init] systemctl restart glassmkr-crucible failed (status=${r.status}). Inspect with: 'systemctl status glassmkr-crucible --no-pager' and 'journalctl -u glassmkr-crucible -n 50 --no-pager'`);
      return 9;
    }
    deps.log(`[init] service enabled and (re)started.`);
  } catch (err: any) {
    deps.error(`[init] failed to enable/restart service: ${err?.message ?? err}`);
    return 9;
  }

  deps.log(`[init] done. Next steps:`);
  deps.log(`  systemctl status glassmkr-crucible --no-pager | head -20`);
  deps.log(`  journalctl -u glassmkr-crucible -n 50 --no-pager`);
  return 0;
}

/**
 * Default IO bindings to the real OS. Used by index.ts when init runs
 * for real; tests pass their own mocks.
 */
export function defaultDeps(): InitDeps {
  return {
    fs: {
      existsSync: fsDefault.existsSync,
      mkdirSync: (p, opts) => { fsDefault.mkdirSync(p, opts); },
      writeFileSync: (p, data, opts) => { fsDefault.writeFileSync(p, data, opts); },
      chmodSync: fsDefault.chmodSync,
      chownSync: fsDefault.chownSync,
      lstatSync: (p) => {
        const s = fsDefault.lstatSync(p);
        return {
          isSymbolicLink: s.isSymbolicLink(),
          isFile: s.isFile(),
          isDirectory: s.isDirectory(),
          uid: s.uid,
          gid: s.gid,
          mode: s.mode,
        };
      },
      realpathSync: fsDefault.realpathSync,
      writeSecureFileSync: (p, data, mode) => {
        const flags = fsDefault.constants.O_CREAT
          | fsDefault.constants.O_EXCL
          | fsDefault.constants.O_WRONLY
          | fsDefault.constants.O_NOFOLLOW;
        let fd: number | undefined;
        try {
          fd = fsDefault.openSync(p, flags, mode);
          const st = fsDefault.fstatSync(fd);
          if (!st.isFile() || st.nlink !== 1 || st.uid !== 0) {
            throw new Error(`refusing unsafe temporary file ${p}`);
          }
          fsDefault.fchmodSync(fd, mode);
          fsDefault.writeFileSync(fd, data, "utf8");
          fsDefault.fsyncSync(fd);
        } finally {
          if (fd !== undefined) fsDefault.closeSync(fd);
        }
      },
      renameSync: fsDefault.renameSync,
      unlinkSync: fsDefault.unlinkSync,
    },
    exec: (cmd, args) => {
      try {
        const stdout = execFileSyncDefault(cmd, args, { encoding: "utf8", env: buildSubprocessEnv() });
        return { stdout, status: 0 };
      } catch (err: any) {
        return { stdout: err?.stdout?.toString() ?? "", status: typeof err?.status === "number" ? err.status : null };
      }
    },
    hostname: () => osDefault.hostname(),
    log: (m) => console.log(m),
    warn: (m) => console.warn(m),
    error: (m) => console.error(m),
    fetch: undiciFetchImpl,
    resolveEndpoint: assertEndpointResolution,
    readStdin: () => new Promise<string>((resolve, reject) => {
      let buf = "";
      process.stdin.setEncoding("utf8");
      process.stdin.on("data", (chunk) => { buf += chunk; });
      process.stdin.on("end", () => resolve(buf));
      process.stdin.on("error", reject);
    }),
    env: process.env,
  };
}

// Marker exports so tsc emits the file even if only used via dynamic import.
export const _typecheck_helpers = { pathDefault, osDefault };
