// `glassmkr-crucible init` subcommand: canonical first-run setup.
//
// Validates the API key, optionally probes the ingest endpoint to
// confirm it's accepted, writes /etc/glassmkr/crucible.yaml (mode
// 0600), writes a systemd unit at /etc/systemd/system/glassmkr-crucible
// (mode 0644) with ExecStart pointing at the dynamically-detected
// binary path (so Debian's /usr/local/bin/ vs Ubuntu's /usr/bin/
// divergence is handled), runs daemon-reload, and (unless --no-start)
// enables-and-starts the service.
//
// Legacy migration: if /etc/glassmkr/collector.yaml exists and the new
// path does not, init renames it via fs.renameSync() before any write.
// This is lossless and atomic on the same filesystem (/etc is always
// one mount). The systemd unit is regenerated to point at the new path
// and daemon-reload picks it up.
//
// Designed to run unprivileged for the validation/connectivity steps
// and require root for the filesystem and systemd writes (same as the
// agent itself). Errors are surfaced with non-zero exit codes.
//
// IO is injected via the InitDeps interface so unit tests can run
// without touching /etc, systemctl, or the network.

import * as fsDefault from "node:fs";
import { execFileSync as execFileSyncDefault } from "node:child_process";
import * as osDefault from "node:os";
import * as pathDefault from "node:path";
import {
  SERVICE_USER, WRAPPER_PATH, WRAPPER_SCRIPT, SUDOERS_PATH, SUDOERS_CONTENT,
} from "./lib/privileged.js";

export const STATE_DIRS = ["/var/lib/glassmkr", "/var/lib/crucible"];

export interface InitOptions {
  apiKey: string; // raw value, may be the literal "-" to mean "read from stdin"
  name?: string;
  ingestUrl?: string;
  configPath?: string;
  noStart?: boolean;
  force?: boolean;
  noVerify?: boolean; // skip the connectivity probe (default: probe)
}

export interface InitDeps {
  fs: {
    existsSync: (p: string) => boolean;
    mkdirSync: (p: string, opts?: { recursive?: boolean; mode?: number }) => void;
    writeFileSync: (p: string, data: string, opts?: { mode?: number }) => void;
    chmodSync: (p: string, mode: number) => void;
    chownSync: (p: string, uid: number, gid: number) => void;
    lstatSync: (p: string) => { isSymbolicLink: boolean; uid: number; gid: number; mode: number };
    renameSync: (from: string, to: string) => void;
  };
  exec: (cmd: string, args: string[]) => { stdout: string; status: number | null };
  hostname: () => string;
  log: (msg: string) => void;
  warn: (msg: string) => void;
  error: (msg: string) => void;
  fetch: (url: string, init: { method: string; headers: Record<string, string>; signal?: AbortSignal }) => Promise<{ status: number }>;
  readStdin: () => Promise<string>;
}

export const DEFAULT_INGEST_URL = "https://app.glassmkr.com/api/v1/ingest";
export const DEFAULT_CONFIG_PATH = "/etc/glassmkr/crucible.yaml";
export const LEGACY_CONFIG_PATH = "/etc/glassmkr/collector.yaml";
export const SYSTEMD_UNIT_PATH = "/etc/systemd/system/glassmkr-crucible.service";

const KEY_RE_NEW = /^gmk_cru_live_[A-Za-z0-9]{20,}_[A-Za-z0-9]{4}$/;
const KEY_RE_LEGACY = /^col_[A-Fa-f0-9]{16,}$/;

export function isValidApiKey(key: string): boolean {
  if (!key || /\s/.test(key)) return false;
  return KEY_RE_NEW.test(key) || KEY_RE_LEGACY.test(key);
}

export function buildCollectorYaml(serverName: string, ingestUrl: string, apiKey: string): string {
  // Hand-written so the format is human-readable, deterministic, and
  // doesn't pull in a YAML serializer at install time. Mirrors the
  // existing /etc/glassmkr/crucible.yaml shape (the file was renamed
  // from collector.yaml to crucible.yaml in v0.13.5; the on-disk
  // content layout did not change).
  return [
    `# Generated by 'glassmkr-crucible init'. Hand-edit if needed.`,
    `server_name: "${escapeDoubleQuoted(serverName)}"`,
    `collection:`,
    `  interval_seconds: 300`,
    `  ipmi: true`,
    `  smart: true`,
    `dashboard:`,
    `  enabled: true`,
    `  url: "${escapeDoubleQuoted(ingestUrl.replace(/\/api\/v1\/ingest$/, ""))}"`,
    `  api_key: "${apiKey}"`,
    ``,
  ].join("\n");
}

function escapeDoubleQuoted(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

export function buildSystemdUnit(binPath: string, configPath: string, user = "root"): string {
  return [
    `[Unit]`,
    `Description=Glassmkr Crucible - Bare Metal Monitoring`,
    `After=network.target`,
    ``,
    `[Service]`,
    `Type=simple`,
    // §2.1: run unprivileged when privilege separation is in place; the
    // agent escalates only through the sudo wrapper. Falls back to root
    // when setup didn't complete, so collection never silently breaks.
    `User=${user}`,
    `ExecStart=${binPath} ${configPath}`,
    `Restart=always`,
    `RestartSec=10`,
    ``,
    `[Install]`,
    `WantedBy=multi-user.target`,
    ``,
  ].join("\n");
}

/**
 * Establish the §2.1 privilege boundary: an unprivileged `glassmkr` system
 * user that escalates only through the sudo wrapper. Idempotent; safe to run
 * on every install/upgrade. Returns true iff the box is fully ready to run
 * the service as `glassmkr` (user + wrapper + valid sudoers + writable state).
 * On ANY hard failure it returns false and the caller keeps the unit on
 * User=root, so an install where this can't complete never loses collection.
 *
 * Ordering matters for the root->unprivileged migration: the wrapper and
 * sudoers are installed BEFORE the unit flips to User=glassmkr (done by the
 * caller), so there is never a window where the agent is unprivileged but the
 * escalation path is absent.
 */
export function setupPrivilegeSeparation(deps: InitDeps, configPath: string): boolean {
  // 1. Service user (system, no login, no home).
  const idr = deps.exec("id", ["-u", SERVICE_USER]);
  if (idr.status !== 0) {
    const ur = deps.exec("useradd", [
      "--system", "--no-create-home", "--shell", "/usr/sbin/nologin", SERVICE_USER,
    ]);
    if (ur.status !== 0) {
      deps.warn(`[init] could not create '${SERVICE_USER}' user (status=${ur.status}); staying on User=root.`);
      return false;
    }
    deps.log(`[init] created system user '${SERVICE_USER}'.`);
  }

  // 2. The collection wrapper. It must end up root-owned, 0755, and NOT a
  //    symlink or writable by the service user, or the sudo grant could be
  //    hijacked. A bare writeFileSync is unsafe: if WRAPPER_PATH already exists
  //    (owned by `glassmkr`) or is a symlink, the write follows/preserves it, so
  //    the file stays service-user-owned while the NOPASSWD sudoers rule below
  //    still gets installed. The service account could then rewrite the wrapper
  //    and run arbitrary code as root. Instead: build a FRESH root-owned temp
  //    file, then atomically rename it into place. rename REPLACES a pre-existing
  //    file or symlink (it does not follow the link), so ownership becomes root
  //    regardless of what was there. Then lstat-verify the final path. The parent
  //    dir (/usr/local/sbin) is root-owned and not service-user-writable, so the
  //    temp path itself cannot be pre-planted. (Codex review 2026-07-17.)
  const wrapperTmp = `${WRAPPER_PATH}.tmp`;
  try {
    deps.fs.writeFileSync(wrapperTmp, WRAPPER_SCRIPT, { mode: 0o755 });
    deps.fs.chmodSync(wrapperTmp, 0o755);
    deps.fs.chownSync(wrapperTmp, 0, 0);
    deps.fs.renameSync(wrapperTmp, WRAPPER_PATH);
    const st = deps.fs.lstatSync(WRAPPER_PATH);
    if (st.isSymbolicLink || st.uid !== 0 || st.gid !== 0 || (st.mode & 0o022) !== 0) {
      deps.warn(`[init] wrapper ${WRAPPER_PATH} failed its post-install safety check (symlink=${st.isSymbolicLink}, uid=${st.uid}, gid=${st.gid}, mode=${(st.mode & 0o777).toString(8)}); staying on User=root.`);
      return false;
    }
  } catch (err: any) {
    deps.warn(`[init] could not install wrapper ${WRAPPER_PATH}: ${err?.message ?? err}; staying on User=root.`);
    return false;
  }

  // 3. Sudoers drop-in, validated with `visudo -cf` on a temp file BEFORE it
  //    goes live (a malformed sudoers file breaks sudo host-wide).
  const sudoersTmp = `${SUDOERS_PATH}.tmp`;
  try {
    deps.fs.writeFileSync(sudoersTmp, SUDOERS_CONTENT, { mode: 0o440 });
    const chk = deps.exec("visudo", ["-cf", sudoersTmp]);
    if (chk.status !== 0) {
      deps.warn(`[init] visudo rejected the sudoers drop-in (status=${chk.status}); staying on User=root.`);
      return false;
    }
    deps.fs.renameSync(sudoersTmp, SUDOERS_PATH);
    deps.fs.chmodSync(SUDOERS_PATH, 0o440);
  } catch (err: any) {
    deps.warn(`[init] could not install sudoers ${SUDOERS_PATH}: ${err?.message ?? err}; staying on User=root.`);
    return false;
  }

  // 4. State dirs the agent writes directly (alert-state, reboot-marker) +
  //    the config it reads: hand ownership to the service user.
  for (const dir of STATE_DIRS) {
    try { deps.fs.mkdirSync(dir, { recursive: true, mode: 0o750 }); } catch { /* exists */ }
    const ch = deps.exec("chown", ["-R", `${SERVICE_USER}:${SERVICE_USER}`, dir]);
    if (ch.status !== 0) {
      deps.warn(`[init] could not chown ${dir} to ${SERVICE_USER} (status=${ch.status}); staying on User=root.`);
      return false;
    }
  }
  const chc = deps.exec("chown", [`${SERVICE_USER}:${SERVICE_USER}`, configPath]);
  if (chc.status !== 0) {
    deps.warn(`[init] could not chown ${configPath} to ${SERVICE_USER}; staying on User=root.`);
    return false;
  }

  // 5. adm group: several collectors read log-adjacent paths directly. Best
  //    effort; not fatal (the wrapper covers the binary paths regardless).
  deps.exec("usermod", ["-aG", "adm", SERVICE_USER]);

  deps.log(`[init] privilege separation ready: service will run as '${SERVICE_USER}' via ${WRAPPER_PATH}.`);
  return true;
}

/**
 * Run the init flow with caller-provided IO. Returns the exit code
 * (0 = success). Pure orchestration; no side effects on `process`.
 */
export async function runInit(opts: InitOptions, deps: InitDeps): Promise<number> {
  // Resolve API key (stdin form supports `--api-key -`).
  let apiKey = opts.apiKey;
  if (apiKey === "-") {
    try {
      apiKey = (await deps.readStdin()).replace(/\r?\n$/, "").trim();
    } catch (err: any) {
      deps.error(`[init] failed to read api key from stdin: ${err?.message ?? err}`);
      return 1;
    }
  }
  if (!isValidApiKey(apiKey)) {
    deps.error(`[init] invalid --api-key: must look like "gmk_cru_live_<...>_<4>" or "col_<hex>". Got ${apiKey.length} char(s).`);
    return 2;
  }

  const ingestUrl = opts.ingestUrl ?? DEFAULT_INGEST_URL;
  const configPath = opts.configPath ?? DEFAULT_CONFIG_PATH;
  const serverName = opts.name && opts.name.trim() ? opts.name.trim() : deps.hostname();

  // Connectivity probe (optional). 401 means key is wrong → hard fail.
  // 5xx / network errors → warn but continue (the host's network may
  // still be coming up during a fresh install).
  if (!opts.noVerify) {
    deps.log(`[init] probing ${ingestUrl} ...`);
    try {
      const ctrl = new AbortController();
      const timer = setTimeout(() => ctrl.abort(), 8000);
      const resp = await deps.fetch(ingestUrl, {
        method: "GET",
        headers: { Authorization: `Bearer ${apiKey}` },
        signal: ctrl.signal,
      });
      clearTimeout(timer);
      if (resp.status === 401 || resp.status === 403) {
        deps.error(`[init] api key rejected by ${ingestUrl} (HTTP ${resp.status}). Double-check the key in your Glassmkr dashboard.`);
        return 3;
      }
      if (resp.status >= 500) {
        deps.warn(`[init] ingest endpoint returned ${resp.status}; continuing anyway. Check connectivity post-install.`);
      } else {
        deps.log(`[init] api key validated (HTTP ${resp.status}).`);
      }
    } catch (err: any) {
      deps.warn(`[init] connectivity probe failed: ${err?.message ?? err}. Continuing; verify after install with 'journalctl -u glassmkr-crucible'.`);
    }
  }

  // Legacy migration: if the operator is initing into the canonical
  // /etc/glassmkr/crucible.yaml path AND a legacy /etc/glassmkr/collector.yaml
  // file is present AND the new file is not, rename it lossless into
  // place. This preserves any hand-edits (telegram tokens, custom
  // thresholds, tls_pin) the operator added since the original install.
  // If both files exist we leave the legacy file alone and warn the
  // operator so they can resolve the divergence; --force on top of a
  // populated new path is the normal overwrite path and the legacy
  // file becomes irrelevant.
  const isCanonicalPath = configPath === DEFAULT_CONFIG_PATH;
  const legacyPresent = isCanonicalPath && deps.fs.existsSync(LEGACY_CONFIG_PATH);
  const newPresent = deps.fs.existsSync(configPath);
  let justMigrated = false;
  if (legacyPresent && !newPresent) {
    try {
      deps.fs.renameSync(LEGACY_CONFIG_PATH, configPath);
      justMigrated = true;
      deps.log(`[init] migrated legacy config: ${LEGACY_CONFIG_PATH} -> ${configPath}`);
    } catch (err: any) {
      deps.error(`[init] failed to migrate legacy config ${LEGACY_CONFIG_PATH} -> ${configPath}: ${err?.message ?? err}`);
      return 6;
    }
  } else if (legacyPresent && newPresent) {
    deps.warn(`[init] both ${LEGACY_CONFIG_PATH} and ${configPath} exist; leaving the legacy file in place. After init, remove the legacy file with: sudo rm ${LEGACY_CONFIG_PATH}`);
  }

  // Write config (0600) — refuse to overwrite without --force. A file
  // that arrived via the legacy migration just above counts as "the
  // operator's existing config" and is preserved without rewrite (the
  // explicit migration log line above tells them what happened).
  if (justMigrated) {
    deps.log(`[init] preserved migrated config at ${configPath} (no rewrite). To regenerate from scratch, re-run with --force.`);
  } else if (deps.fs.existsSync(configPath) && !opts.force) {
    deps.error(`[init] config already exists at ${configPath}. Pass --force to overwrite, or remove the file first.`);
    return 4;
  }

  const parent = pathDefault.dirname(configPath);
  try {
    deps.fs.mkdirSync(parent, { recursive: true, mode: 0o755 });
  } catch (err: any) {
    deps.error(`[init] failed to create config directory ${parent}: ${err?.message ?? err}`);
    return 5;
  }

  // Skip rewrite when we just migrated the legacy file into place;
  // operator-edited content (telegram tokens, custom thresholds, tls_pin)
  // is preserved verbatim. --force still re-generates from scratch by
  // overwriting unconditionally.
  if (!justMigrated || opts.force) {
    const yaml = buildCollectorYaml(serverName, ingestUrl, apiKey);
    try {
      deps.fs.writeFileSync(configPath, yaml, { mode: 0o600 });
      deps.fs.chmodSync(configPath, 0o600);
      deps.log(`[init] wrote config: ${configPath} (mode 0600, server_name=${serverName})`);
    } catch (err: any) {
      deps.error(`[init] failed to write ${configPath}: ${err?.message ?? err}`);
      return 6;
    }
  }

  // Resolve binary path via `command -v`. Mirrors the F5 install fix.
  let binPath: string | null = null;
  try {
    const r = deps.exec("command", ["-v", "glassmkr-crucible"]);
    const candidate = r.stdout.trim();
    if (candidate) binPath = candidate;
  } catch {
    // fall through; we'll try `which` next
  }
  if (!binPath) {
    try {
      const r = deps.exec("which", ["glassmkr-crucible"]);
      const candidate = r.stdout.trim();
      if (candidate) binPath = candidate;
    } catch {
      // ignored
    }
  }
  if (!binPath) {
    deps.error(`[init] could not locate the glassmkr-crucible binary on PATH. Make sure 'npm install -g @glassmkr/crucible' completed before running init.`);
    return 7;
  }

  // §2.1: establish the unprivileged-user + sudo-wrapper boundary. Runs
  // AFTER the config is written (so it can hand ownership to the service
  // user) and BEFORE the unit is written (so the escalation path exists
  // before the unit flips to User=glassmkr). Fail-safe: on any hard failure
  // this returns false and the unit stays on User=root.
  const serviceUser = setupPrivilegeSeparation(deps, configPath) ? SERVICE_USER : "root";

  // Write systemd unit (0644).
  const unit = buildSystemdUnit(binPath, configPath, serviceUser);
  try {
    deps.fs.writeFileSync(SYSTEMD_UNIT_PATH, unit, { mode: 0o644 });
    deps.fs.chmodSync(SYSTEMD_UNIT_PATH, 0o644);
    deps.log(`[init] wrote systemd unit: ${SYSTEMD_UNIT_PATH} (ExecStart=${binPath})`);
  } catch (err: any) {
    deps.error(`[init] failed to write systemd unit: ${err?.message ?? err}`);
    return 8;
  }

  // daemon-reload to pick up the new unit.
  try {
    const r = deps.exec("systemctl", ["daemon-reload"]);
    if (r.status !== 0) {
      deps.warn(`[init] systemctl daemon-reload returned ${r.status}; continuing.`);
    }
  } catch (err: any) {
    deps.warn(`[init] systemctl daemon-reload failed: ${err?.message ?? err}; continuing.`);
  }

  if (opts.noStart) {
    deps.log(`[init] --no-start set; not enabling/starting glassmkr-crucible.`);
    deps.log(`[init] when ready: 'sudo systemctl enable --now glassmkr-crucible'`);
    return 0;
  }

  try {
    const r = deps.exec("systemctl", ["enable", "--now", "glassmkr-crucible"]);
    if (r.status !== 0) {
      deps.error(`[init] systemctl enable --now glassmkr-crucible failed (status=${r.status}). Inspect with: 'systemctl status glassmkr-crucible --no-pager' and 'journalctl -u glassmkr-crucible -n 50 --no-pager'`);
      return 9;
    }
    deps.log(`[init] service enabled and started.`);
  } catch (err: any) {
    deps.error(`[init] failed to enable/start service: ${err?.message ?? err}`);
    return 9;
  }

  deps.log(`[init] done. Next steps:`);
  deps.log(`  systemctl status glassmkr-crucible --no-pager | head -20`);
  deps.log(`  journalctl -u glassmkr-crucible -n 50 --no-pager`);
  return 0;
}

/**
 * Default IO bindings to the real OS. Used by index.ts when init runs
 * for real; tests pass their own mocks.
 */
export function defaultDeps(): InitDeps {
  return {
    fs: {
      existsSync: fsDefault.existsSync,
      mkdirSync: (p, opts) => { fsDefault.mkdirSync(p, opts); },
      writeFileSync: (p, data, opts) => { fsDefault.writeFileSync(p, data, opts); },
      chmodSync: fsDefault.chmodSync,
      chownSync: fsDefault.chownSync,
      lstatSync: (p) => {
        const s = fsDefault.lstatSync(p);
        return { isSymbolicLink: s.isSymbolicLink(), uid: s.uid, gid: s.gid, mode: s.mode };
      },
      renameSync: fsDefault.renameSync,
    },
    exec: (cmd, args) => {
      try {
        const stdout = execFileSyncDefault(cmd, args, { encoding: "utf8" });
        return { stdout, status: 0 };
      } catch (err: any) {
        return { stdout: err?.stdout?.toString() ?? "", status: typeof err?.status === "number" ? err.status : null };
      }
    },
    hostname: () => osDefault.hostname(),
    log: (m) => console.log(m),
    warn: (m) => console.warn(m),
    error: (m) => console.error(m),
    fetch: async (url, init) => {
      const r = await fetch(url, init as any);
      return { status: r.status };
    },
    readStdin: () => new Promise<string>((resolve, reject) => {
      let buf = "";
      process.stdin.setEncoding("utf8");
      process.stdin.on("data", (chunk) => { buf += chunk; });
      process.stdin.on("end", () => resolve(buf));
      process.stdin.on("error", reject);
    }),
  };
}

// Marker exports so tsc emits the file even if only used via dynamic import.
export const _typecheck_helpers = { pathDefault, osDefault };
