name: Publish to npm

on:
  push:
    tags: ['v*']

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: npm publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          # Node 24 ships with npm 11.x which has working npm Trusted Publishing.
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - run: npm --version
      - run: npm install
      - run: npm run build
      - run: npm publish --access public --provenance
